version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      day: sunday
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "DBot GH Actions"
