name: Deploy to Staging

on:
  push:
    branches:
      - staging

env:
  API_URL: https://api.staging.emeris.com/v1

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn generate:env

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_EMERIS_PROD }}"
          target: emeris-admin-staging
          channelId: live
          projectId: emeris-prod
